### ISSUE TITLE
Viewport meta tag

### ISSUE THREAD

**Issue by ghost** [jsharris1229/colmaracademy#1]
https://github.com/jsharris1229/colmaracademy/blob/master/index.html#L3-L18

Don't forget to include the viewport meta tag so that you can properly control the viewport's size and scale.

This is a _must_ for any mobile-optimized site.

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

**Comment by jsharris1229** [comment]
Thanks. I must have missed this in the lessons. I'll research it and add it to the code.
