### ISSUE TITLE
Mobile responsiveness

### ISSUE THREAD

**Issue by ghost** [jsharris1229/colmaracademy#4]
You've successfully built the desktop and mobile sites, but there is still work to be done so that your site resizes _gracefully_.

Make sure to resize and test your website at different sizes so that you can provide the smoothest experience possible.

<img width="622" alt="screen shot 2018-01-09 at 11 09 58 pm" src="https://user-images.githubusercontent.com/7355203/34755560-c19309a8-f592-11e7-90bc-356872ca5ae5.png">

**Comment by jsharris1229** [comment]
I agree. I spent too much time on things like adding box-shadow to elements, working on :hover and exploring variables. On Monday, I was out of time and decided to submit what I had. Thank you for taking the time to thoroughly review my project. This has been great and I'll be signing up for the next intensive course. The projects and reviews are very helpful.
